-- Receita: uma preparacao montada a partir de outros alimentos.
--
-- A receita NAO e uma entidade paralela ao alimento — ela e um alimento, com
-- fonte RECEITA e composicao calculada em vez de tabelada. A escolha faz com
-- que tudo que ja existe passe a valer para ela sem uma linha a mais: aparece
-- na busca, aceita medida caseira, entra numa refeicao, e a prescricao carrega
-- a procedencia "Receita calculada" do mesmo jeito que carrega "TACO".
--
-- O que a receita acrescenta ao alimento sao tres colunas esparsas — nulas nos
-- 23.945 registros das tabelas de referencia — e a lista de ingredientes.

ALTER TABLE alimento ADD COLUMN modo_preparo VARCHAR(4000);

-- Peso da preparacao pronta. Nao e a soma dos ingredientes: cozinhar perde ou
-- ganha agua, e 500 g de arroz cru nao viram 500 g de arroz cozido. Nulo
-- significa que o nutricionista nao informou, e nesse caso a soma dos
-- ingredientes e usada como estimativa — o que a interface precisa dizer, em
-- vez de apresentar o numero como se fosse medido.
ALTER TABLE alimento ADD COLUMN rendimento_gramas DECIMAL(12,3);

-- Em quantas porcoes a preparacao rende. Serve para derivar a medida caseira
-- "1 porcao", que e como a receita chega ao paciente.
ALTER TABLE alimento ADD COLUMN porcoes INTEGER;

CREATE TABLE ingrediente_receita (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receita_id        BIGINT        NOT NULL,
    alimento_id       BIGINT        NOT NULL,
    medida_id         BIGINT,
    -- Rotulo da medida no momento em que a receita foi montada. Repete o que
    -- esta em medida_caseira pelo mesmo motivo do item de refeicao: a medida
    -- pode ser corrigida ou removida depois, e a receita continua tendo de
    -- dizer "2 colheres de sopa" para quem a le.
    descricao_medida  VARCHAR(120),
    quantidade        DECIMAL(12,3) NOT NULL,
    -- Peso do ingrediente, resolvido na gravacao. Guardado, e nao derivado a
    -- cada leitura, para que corrigir o peso de uma medida caseira depois nao
    -- altere em silencio a composicao de uma receita ja montada.
    gramas            DECIMAL(12,3) NOT NULL,
    ordem             INTEGER       NOT NULL,
    criado_em         TIMESTAMP     NOT NULL,
    atualizado_em     TIMESTAMP,
    criado_por        VARCHAR(180),
    atualizado_por    VARCHAR(180),
    CONSTRAINT fk_ingrediente_receita  FOREIGN KEY (receita_id)  REFERENCES alimento (id),
    CONSTRAINT fk_ingrediente_alimento FOREIGN KEY (alimento_id) REFERENCES alimento (id),
    CONSTRAINT ck_ingrediente_quantidade CHECK (quantidade > 0),
    CONSTRAINT ck_ingrediente_gramas     CHECK (gramas > 0)
);

CREATE INDEX ix_ingrediente_receita  ON ingrediente_receita (receita_id);
CREATE INDEX ix_ingrediente_alimento ON ingrediente_receita (alimento_id);

-- Rendimento tem de ser positivo quando informado.
ALTER TABLE alimento ADD CONSTRAINT ck_alimento_rendimento
    CHECK (rendimento_gramas IS NULL OR rendimento_gramas > 0);
ALTER TABLE alimento ADD CONSTRAINT ck_alimento_porcoes
    CHECK (porcoes IS NULL OR porcoes > 0);
