-- Nota: quebra de linha e chr(10) e nao CHAR(10).
--
-- No H2, CHAR(10) e a funcao que devolve o caractere de codigo 10. No
-- PostgreSQL, CHAR(10) e a declaracao de um tipo de dez caracteres, e a
-- concatenacao vira erro de sintaxe. chr(10) e a mesma funcao nos dois.
-- Isto so apareceu quando as migracoes rodaram num PostgreSQL de verdade:
-- o H2 em modo de compatibilidade aceitava a forma que o Postgres recusa.
--
-- Orientacoes nutricionais: os textos que o nutricionista entrega junto do plano.
--
-- Sao duas tabelas e nao uma porque servem a dois momentos diferentes. A
-- biblioteca guarda o texto que o consultorio reaproveita; a orientacao do
-- plano guarda o texto que um paciente especifico recebeu.
--
-- A copia entre as duas e deliberada. Se o plano apenas apontasse para a
-- biblioteca, corrigir um modelo mudaria em silencio o que dezenas de pacientes
-- ja receberam — inclusive planos encerrados, que sao registro do que foi
-- prescrito. E a mesma razao pela qual o item de refeicao grava o peso.

CREATE TABLE orientacao (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Nulo identifica modelo do sistema, visivel a todos os consultorios.
    -- Preenchido, so o consultorio dono a enxerga. Mesmo eixo do acervo de
    -- alimentos e das medidas caseiras.
    conta_id       BIGINT,
    titulo         VARCHAR(150)  NOT NULL,
    corpo          VARCHAR(8000) NOT NULL,
    ativo          BOOLEAN       NOT NULL DEFAULT TRUE,
    criado_em      TIMESTAMP     NOT NULL,
    atualizado_em  TIMESTAMP,
    criado_por     VARCHAR(180),
    atualizado_por VARCHAR(180),
    CONSTRAINT fk_orientacao_conta FOREIGN KEY (conta_id) REFERENCES conta (id)
);

CREATE INDEX ix_orientacao_conta ON orientacao (conta_id);

CREATE TABLE orientacao_do_plano (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plano_id       BIGINT        NOT NULL,
    -- Procedencia, nao dependencia: pode ficar nulo se o modelo de origem for
    -- removido, e o texto entregue continua intacto.
    orientacao_id  BIGINT,
    titulo         VARCHAR(150)  NOT NULL,
    corpo          VARCHAR(8000) NOT NULL,
    ordem          INTEGER       NOT NULL,
    criado_em      TIMESTAMP     NOT NULL,
    atualizado_em  TIMESTAMP,
    criado_por     VARCHAR(180),
    atualizado_por VARCHAR(180),
    CONSTRAINT fk_orientacao_plano_plano FOREIGN KEY (plano_id)
        REFERENCES plano_alimentar (id),
    CONSTRAINT fk_orientacao_plano_origem FOREIGN KEY (orientacao_id)
        REFERENCES orientacao (id)
);

CREATE INDEX ix_orientacao_plano ON orientacao_do_plano (plano_id);

-- Modelos que acompanham o sistema (conta_id nulo). Sao ponto de partida
-- editavel, e nao prescricao: o nutricionista copia e adapta ao paciente.
INSERT INTO orientacao (conta_id, titulo, corpo, ativo, criado_em) VALUES
(NULL, 'Como montar o prato',
 'Divida o prato em quatro partes iguais.' || chr(10) ||
 'Duas partes de legumes e verduras, cruas ou cozidas.' || chr(10) ||
 'Uma parte de arroz, macarrao, batata, mandioca ou pao.' || chr(10) ||
 'Uma parte de carne, ovo, peixe ou leguminosas.' || chr(10) || chr(10) ||
 'Sirva-se uma vez so e coma sentado, sem tela por perto.',
 TRUE, CURRENT_TIMESTAMP),
(NULL, 'Hidratacao ao longo do dia',
 'Beba de 30 a 35 ml de agua por quilo de peso, distribuidos no dia.' || chr(10) ||
 'Deixe uma garrafa a vista: sede nao e um bom aviso, ela chega tarde.' || chr(10) ||
 'Cha sem acucar e agua de coco contam. Refrigerante e suco de caixa, nao.',
 TRUE, CURRENT_TIMESTAMP),
(NULL, 'Leitura de rotulo',
 'Olhe primeiro a lista de ingredientes, e nao a tabela nutricional.' || chr(10) ||
 'Os ingredientes vem em ordem de quantidade: o primeiro e o que mais tem.' || chr(10) ||
 'Acucar aparece com muitos nomes — xarope de glicose, dextrose, maltodextrina.' || chr(10) ||
 'Quanto mais curta a lista, menos processado o produto.',
 TRUE, CURRENT_TIMESTAMP),
(NULL, 'Organizacao das compras',
 'Faca a lista antes de sair e nao va ao mercado com fome.' || chr(10) ||
 'Circule pelas bordas do mercado: e onde ficam hortifruti, carnes e laticinios.' || chr(10) ||
 'Deixe legumes lavados e porcionados assim que chegar em casa.',
 TRUE, CURRENT_TIMESTAMP),
(NULL, 'Comer fora de casa',
 'Escolha o prato antes de sentar, olhando o cardapio com calma.' || chr(10) ||
 'Peca o molho a parte e prefira grelhado a frito.' || chr(10) ||
 'Uma refeicao fora do plano nao desfaz a semana. Retome na proxima.',
 TRUE, CURRENT_TIMESTAMP);
