-- Exames laboratoriais.
--
-- Tres tabelas: o catalogo de parametros, as faixas de referencia de cada um, e
-- o resultado registrado para um paciente.
--
-- ATENCAO A UMA ARMADILHA CLINICA: faixa de referencia nao e universal. Ela
-- depende do metodo do laboratorio, do equipamento e da populacao de
-- referencia, e muda com o tempo. As faixas semeadas aqui sao as usualmente
-- citadas para adulto e servem de ponto de partida — o laudo do laboratorio
-- prevalece sobre elas.
--
-- E justamente por isso que EXAME grava a faixa que usou junto do valor. Se a
-- classificacao fosse calculada na leitura, corrigir uma faixa cadastrada
-- reclassificaria exames antigos: um resultado que era normal apareceria
-- alterado sem que nada tivesse acontecido com o paciente.

CREATE TABLE parametro_exame (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Nulo identifica parametro do catalogo do sistema, comum a todos.
    conta_id       BIGINT,
    nome           VARCHAR(120) NOT NULL,
    -- Usada para comparar series: valor em outra unidade nao entra na mesma
    -- linha do tempo.
    unidade_padrao VARCHAR(20)  NOT NULL,
    grupo          VARCHAR(60),
    ativo          BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em      TIMESTAMP    NOT NULL,
    atualizado_em  TIMESTAMP,
    criado_por     VARCHAR(180),
    atualizado_por VARCHAR(180),
    CONSTRAINT fk_parametro_conta FOREIGN KEY (conta_id) REFERENCES conta (id)
);

CREATE INDEX ix_parametro_conta ON parametro_exame (conta_id);

CREATE TABLE faixa_referencia (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parametro_id   BIGINT       NOT NULL,
    -- Nulo vale para os dois sexos.
    sexo           VARCHAR(10),
    idade_min      INTEGER,
    idade_max      INTEGER,
    -- Nulo em qualquer extremo significa "sem limite desse lado": LDL nao tem
    -- minimo de preocupacao, e o valor de referencia e "abaixo de 130".
    minimo         DECIMAL(12,3),
    maximo         DECIMAL(12,3),
    criado_em      TIMESTAMP    NOT NULL,
    atualizado_em  TIMESTAMP,
    criado_por     VARCHAR(180),
    atualizado_por VARCHAR(180),
    CONSTRAINT fk_faixa_parametro FOREIGN KEY (parametro_id) REFERENCES parametro_exame (id),
    CONSTRAINT ck_faixa_limites CHECK (minimo IS NOT NULL OR maximo IS NOT NULL)
);

CREATE INDEX ix_faixa_parametro ON faixa_referencia (parametro_id);

CREATE TABLE exame (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conta_id       BIGINT       NOT NULL,
    paciente_id    BIGINT       NOT NULL,
    parametro_id   BIGINT       NOT NULL,
    data_coleta    DATE         NOT NULL,
    -- Nulo significa parametro pedido e ainda nao determinado. Nunca zero:
    -- zero e um resultado, ausencia e outra coisa.
    valor          DECIMAL(12,3),
    unidade        VARCHAR(20)  NOT NULL,
    -- ABAIXO | NORMAL | ACIMA. Nulo quando nao havia faixa cadastrada.
    classificacao  VARCHAR(10),
    -- A faixa usada, congelada na entrada.
    referencia_min DECIMAL(12,3),
    referencia_max DECIMAL(12,3),
    observacao     VARCHAR(1000),
    -- Nome e tipo ficam aqui para que "tem laudo?" seja gratuito na listagem.
    -- O binario mora em laudo_exame, que nenhuma listagem toca.
    laudo_nome     VARCHAR(200),
    laudo_tipo     VARCHAR(100),
    criado_em      TIMESTAMP    NOT NULL,
    atualizado_em  TIMESTAMP,
    criado_por     VARCHAR(180),
    atualizado_por VARCHAR(180),
    CONSTRAINT fk_exame_conta     FOREIGN KEY (conta_id)     REFERENCES conta (id),
    CONSTRAINT fk_exame_paciente  FOREIGN KEY (paciente_id)  REFERENCES paciente (id),
    CONSTRAINT fk_exame_parametro FOREIGN KEY (parametro_id) REFERENCES parametro_exame (id)
);

CREATE INDEX ix_exame_conta    ON exame (conta_id);
CREATE INDEX ix_exame_paciente ON exame (paciente_id, data_coleta);

-- O laudo em tabela separada, e nao em coluna de exame.
--
-- Guardar binario no banco e uma escolha consciente: para um consultorio — umas
-- dezenas de laudos por mes, poucas centenas de KB cada — o custo e baixo e a
-- vantagem e concreta, porque o backup do banco leva os laudos junto, sem um
-- segundo sistema para lembrar de copiar.
--
-- Mas em tabela propria: se o binario ficasse em exame, toda listagem de
-- resultados arrastaria os arquivos junto. BYTEA e nao BLOB porque o dialeto
-- comum a H2 e PostgreSQL e esse (AD-11).
CREATE TABLE laudo_exame (
    exame_id       BIGINT PRIMARY KEY,
    conteudo       BYTEA     NOT NULL,
    criado_em      TIMESTAMP NOT NULL,
    atualizado_em  TIMESTAMP,
    criado_por     VARCHAR(180),
    atualizado_por VARCHAR(180),
    CONSTRAINT fk_laudo_exame FOREIGN KEY (exame_id) REFERENCES exame (id)
);

-- Solicitacao: o pedido que o nutricionista entrega ao paciente.
CREATE TABLE solicitacao_exame (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conta_id       BIGINT       NOT NULL,
    paciente_id    BIGINT       NOT NULL,
    data           DATE         NOT NULL,
    observacao     VARCHAR(1000),
    criado_em      TIMESTAMP    NOT NULL,
    atualizado_em  TIMESTAMP,
    criado_por     VARCHAR(180),
    atualizado_por VARCHAR(180),
    CONSTRAINT fk_solicitacao_conta    FOREIGN KEY (conta_id)    REFERENCES conta (id),
    CONSTRAINT fk_solicitacao_paciente FOREIGN KEY (paciente_id) REFERENCES paciente (id)
);

CREATE INDEX ix_solicitacao_paciente ON solicitacao_exame (paciente_id, data);

CREATE TABLE parametro_solicitado (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solicitacao_id  BIGINT NOT NULL,
    parametro_id    BIGINT NOT NULL,
    criado_em       TIMESTAMP NOT NULL,
    atualizado_em   TIMESTAMP,
    criado_por      VARCHAR(180),
    atualizado_por  VARCHAR(180),
    CONSTRAINT fk_solicitado_solicitacao FOREIGN KEY (solicitacao_id)
        REFERENCES solicitacao_exame (id),
    CONSTRAINT fk_solicitado_parametro FOREIGN KEY (parametro_id)
        REFERENCES parametro_exame (id)
);

CREATE INDEX ix_solicitado_solicitacao ON parametro_solicitado (solicitacao_id);

-- ---------------------------------------------------------------------------
-- Catalogo do sistema. Faixas usualmente citadas para adulto; o laudo do
-- laboratorio prevalece, e por isso a faixa usada vai gravada em cada exame.
-- ---------------------------------------------------------------------------

INSERT INTO parametro_exame (conta_id, nome, unidade_padrao, grupo, ativo, criado_em) VALUES
(NULL, 'Glicemia de jejum',        'mg/dL',   'Metabolismo glicídico', TRUE, CURRENT_TIMESTAMP),
(NULL, 'Hemoglobina glicada',      '%',       'Metabolismo glicídico', TRUE, CURRENT_TIMESTAMP),
(NULL, 'Insulina de jejum',        'µU/mL',   'Metabolismo glicídico', TRUE, CURRENT_TIMESTAMP),
(NULL, 'Colesterol total',         'mg/dL',   'Perfil lipídico',       TRUE, CURRENT_TIMESTAMP),
(NULL, 'LDL-colesterol',           'mg/dL',   'Perfil lipídico',       TRUE, CURRENT_TIMESTAMP),
(NULL, 'HDL-colesterol',           'mg/dL',   'Perfil lipídico',       TRUE, CURRENT_TIMESTAMP),
(NULL, 'Triglicerídeos',           'mg/dL',   'Perfil lipídico',       TRUE, CURRENT_TIMESTAMP),
(NULL, 'Hemoglobina',              'g/dL',    'Hemograma',             TRUE, CURRENT_TIMESTAMP),
(NULL, 'Hematócrito',              '%',       'Hemograma',             TRUE, CURRENT_TIMESTAMP),
(NULL, 'Ferritina',                'ng/mL',   'Ferro',                 TRUE, CURRENT_TIMESTAMP),
(NULL, 'Ferro sérico',             'µg/dL',   'Ferro',                 TRUE, CURRENT_TIMESTAMP),
(NULL, 'Vitamina D (25-OH)',       'ng/mL',   'Vitaminas e minerais',  TRUE, CURRENT_TIMESTAMP),
(NULL, 'Vitamina B12',             'pg/mL',   'Vitaminas e minerais',  TRUE, CURRENT_TIMESTAMP),
(NULL, 'Ácido fólico',             'ng/mL',   'Vitaminas e minerais',  TRUE, CURRENT_TIMESTAMP),
(NULL, 'Cálcio total',             'mg/dL',   'Vitaminas e minerais',  TRUE, CURRENT_TIMESTAMP),
(NULL, 'Magnésio',                 'mg/dL',   'Vitaminas e minerais',  TRUE, CURRENT_TIMESTAMP),
(NULL, 'Zinco',                    'µg/dL',   'Vitaminas e minerais',  TRUE, CURRENT_TIMESTAMP),
(NULL, 'TSH',                      'mUI/L',   'Tireoide',              TRUE, CURRENT_TIMESTAMP),
(NULL, 'T4 livre',                 'ng/dL',   'Tireoide',              TRUE, CURRENT_TIMESTAMP),
(NULL, 'Creatinina',               'mg/dL',   'Função renal',          TRUE, CURRENT_TIMESTAMP),
(NULL, 'Ureia',                    'mg/dL',   'Função renal',          TRUE, CURRENT_TIMESTAMP),
(NULL, 'Ácido úrico',              'mg/dL',   'Função renal',          TRUE, CURRENT_TIMESTAMP),
(NULL, 'AST (TGO)',                'U/L',     'Função hepática',       TRUE, CURRENT_TIMESTAMP),
(NULL, 'ALT (TGP)',                'U/L',     'Função hepática',       TRUE, CURRENT_TIMESTAMP),
(NULL, 'Gama-GT',                  'U/L',     'Função hepática',       TRUE, CURRENT_TIMESTAMP),
(NULL, 'Albumina',                 'g/dL',    'Proteínas',             TRUE, CURRENT_TIMESTAMP),
(NULL, 'Proteína C reativa',       'mg/L',    'Inflamação',            TRUE, CURRENT_TIMESTAMP),
(NULL, 'Homocisteína',             'µmol/L',  'Inflamação',            TRUE, CURRENT_TIMESTAMP),
(NULL, 'Sódio',                    'mEq/L',   'Eletrólitos',           TRUE, CURRENT_TIMESTAMP),
(NULL, 'Potássio',                 'mEq/L',   'Eletrólitos',           TRUE, CURRENT_TIMESTAMP);

-- Faixas iguais para os dois sexos (sexo nulo).
INSERT INTO faixa_referencia (parametro_id, sexo, minimo, maximo, criado_em)
SELECT id, NULL, m.minimo, m.maximo, CURRENT_TIMESTAMP FROM parametro_exame
JOIN (
    SELECT 'Glicemia de jejum'   AS n, 70.0   AS minimo, 99.0   AS maximo UNION ALL
    SELECT 'Hemoglobina glicada',      CAST(NULL AS DECIMAL(12,3)), 5.6   UNION ALL
    SELECT 'Insulina de jejum',        2.6,    24.9   UNION ALL
    SELECT 'Colesterol total',         CAST(NULL AS DECIMAL(12,3)), 190.0 UNION ALL
    SELECT 'LDL-colesterol',           CAST(NULL AS DECIMAL(12,3)), 130.0 UNION ALL
    SELECT 'Triglicerídeos',           CAST(NULL AS DECIMAL(12,3)), 150.0 UNION ALL
    SELECT 'Vitamina D (25-OH)',       30.0,   100.0  UNION ALL
    SELECT 'Vitamina B12',             200.0,  900.0  UNION ALL
    SELECT 'Ácido fólico',             3.0,    17.0   UNION ALL
    SELECT 'Cálcio total',             8.5,    10.5   UNION ALL
    SELECT 'Magnésio',                 1.6,    2.6    UNION ALL
    SELECT 'Zinco',                    70.0,   120.0  UNION ALL
    SELECT 'TSH',                      0.4,    4.0    UNION ALL
    SELECT 'T4 livre',                 0.7,    1.8    UNION ALL
    SELECT 'Ureia',                    15.0,   45.0   UNION ALL
    SELECT 'AST (TGO)',                5.0,    40.0   UNION ALL
    SELECT 'ALT (TGP)',                7.0,    56.0   UNION ALL
    SELECT 'Albumina',                 3.5,    5.2    UNION ALL
    SELECT 'Proteína C reativa',       CAST(NULL AS DECIMAL(12,3)), 3.0 UNION ALL
    SELECT 'Homocisteína',             5.0,    15.0   UNION ALL
    SELECT 'Sódio',                    135.0,  145.0  UNION ALL
    SELECT 'Potássio',                 3.5,    5.1
) m ON m.n = parametro_exame.nome
WHERE parametro_exame.conta_id IS NULL;

-- Faixas que dependem do sexo.
INSERT INTO faixa_referencia (parametro_id, sexo, minimo, maximo, criado_em)
SELECT id, m.sexo, m.minimo, m.maximo, CURRENT_TIMESTAMP FROM parametro_exame
JOIN (
    SELECT 'HDL-colesterol' AS n, 'MASCULINO' AS sexo, 40.0 AS minimo,
           CAST(NULL AS DECIMAL(12,3)) AS maximo UNION ALL
    SELECT 'HDL-colesterol', 'FEMININO',  50.0,  CAST(NULL AS DECIMAL(12,3)) UNION ALL
    SELECT 'Hemoglobina',    'MASCULINO', 13.5,  17.5  UNION ALL
    SELECT 'Hemoglobina',    'FEMININO',  12.0,  16.0  UNION ALL
    SELECT 'Hematócrito',    'MASCULINO', 41.0,  53.0  UNION ALL
    SELECT 'Hematócrito',    'FEMININO',  36.0,  46.0  UNION ALL
    SELECT 'Ferritina',      'MASCULINO', 30.0,  400.0 UNION ALL
    SELECT 'Ferritina',      'FEMININO',  15.0,  150.0 UNION ALL
    SELECT 'Ferro sérico',   'MASCULINO', 65.0,  175.0 UNION ALL
    SELECT 'Ferro sérico',   'FEMININO',  50.0,  170.0 UNION ALL
    SELECT 'Creatinina',     'MASCULINO', 0.7,   1.3   UNION ALL
    SELECT 'Creatinina',     'FEMININO',  0.6,   1.1   UNION ALL
    SELECT 'Ácido úrico',    'MASCULINO', 3.4,   7.0   UNION ALL
    SELECT 'Ácido úrico',    'FEMININO',  2.4,   6.0   UNION ALL
    SELECT 'Gama-GT',        'MASCULINO', 8.0,   61.0  UNION ALL
    SELECT 'Gama-GT',        'FEMININO',  5.0,   36.0
) m ON m.n = parametro_exame.nome
WHERE parametro_exame.conta_id IS NULL;
