-- Curvas de crescimento da OMS e acompanhamento gestacional.
--
-- Ate aqui o sistema recusava classificar quem tem menos de 20 anos, porque a
-- faixa adulta do IMC nao se aplica a quem ainda cresce. Recusar era correto e
-- resolvia pela metade: uma faixa etaria inteira ficava sem leitura.
--
-- As tabelas LMS vem de duas referencias distintas da OMS — os padroes de 2006
-- (0 a 5 anos) e a referencia de 2007 (5 a 19 anos) — e por isso a curva usada
-- fica gravada com o resultado, como ja acontece com o protocolo de dobras.

CREATE TABLE curva_crescimento (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- IMC_PARA_IDADE | ESTATURA_PARA_IDADE
    indicador      VARCHAR(30)   NOT NULL,
    sexo           VARCHAR(10)   NOT NULL,
    -- Idade em meses completos, de 0 a 228.
    mes            INTEGER       NOT NULL,
    -- Parametros da distribuicao LMS: assimetria, mediana e coeficiente de
    -- variacao. O escore-z sai deles, e nao de uma tabela de pontos de corte.
    l              DECIMAL(12,6) NOT NULL,
    m              DECIMAL(12,6) NOT NULL,
    s              DECIMAL(12,6) NOT NULL,
    criado_em      TIMESTAMP     NOT NULL,
    atualizado_em  TIMESTAMP,
    criado_por     VARCHAR(180),
    atualizado_por VARCHAR(180),
    CONSTRAINT uk_curva UNIQUE (indicador, sexo, mes)
);

CREATE INDEX ix_curva_busca ON curva_crescimento (indicador, sexo, mes);

-- Acompanhamento gestacional na propria avaliacao antropometrica: sao as
-- mesmas medidas, lidas contra outra referencia.
ALTER TABLE avaliacao_antropometrica
    ADD COLUMN semana_gestacional INTEGER;
ALTER TABLE avaliacao_antropometrica
    ADD COLUMN peso_pre_gestacional_kg DECIMAL(6,2);

ALTER TABLE avaliacao_antropometrica ADD CONSTRAINT ck_semana_gestacional
    CHECK (semana_gestacional IS NULL OR (semana_gestacional BETWEEN 1 AND 42));
ALTER TABLE avaliacao_antropometrica ADD CONSTRAINT ck_peso_pre_gestacional
    CHECK (peso_pre_gestacional_kg IS NULL OR peso_pre_gestacional_kg > 0);
