-- Recuperacao de senha.
--
-- Duas decisoes de seguranca estao no formato desta tabela.
--
-- Primeira: guarda o hash do token, e nao o token. Quem ler o banco — um dump
-- vazado, um backup mal guardado — nao consegue redefinir a senha de ninguem.
-- E a mesma razao pela qual a senha e guardada como hash.
--
-- Segunda: usado_em existe para que o token valha uma vez so. Sem isso, um link
-- que ficou no historico do navegador ou numa caixa de e-mail continuaria
-- abrindo a porta depois de ja ter sido usado.

CREATE TABLE token_de_recuperacao (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id     BIGINT       NOT NULL,
    token_hash     VARCHAR(64)  NOT NULL,
    expira_em      TIMESTAMP    NOT NULL,
    usado_em       TIMESTAMP,
    criado_em      TIMESTAMP    NOT NULL,
    atualizado_em  TIMESTAMP,
    criado_por     VARCHAR(180),
    atualizado_por VARCHAR(180),
    CONSTRAINT fk_recuperacao_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id),
    CONSTRAINT uk_recuperacao_hash UNIQUE (token_hash)
);

CREATE INDEX ix_recuperacao_usuario ON token_de_recuperacao (usuario_id);

-- Invalidacao das sessoes abertas quando a senha muda.
--
-- O sistema autentica sem estado: nao ha lista de sessoes para encerrar. Mas
-- trocar a senha precisa derrubar quem esta dentro, senao quem obteve a senha
-- antiga continua ate o token expirar sozinho.
--
-- E um contador, e nao um horario. Comparar a emissao do token com a data da
-- troca parece resolver e nao resolve: a data de emissao do JWT tem precisao de
-- segundo, por definicao do formato, enquanto a troca acontece com precisao de
-- milissegundo. Nessa diferenca cabem os dois erros opostos — deslogar o
-- usuario no instante seguinte a ele redefinir a propria senha, ou deixar viva
-- a sessao que se queria derrubar. O contador nao tem casas decimais e nao tem
-- esse problema: ou o token traz a versao vigente, ou nao traz.
ALTER TABLE usuario ADD COLUMN senha_versao INTEGER DEFAULT 0 NOT NULL;

-- O horario continua, como informacao de auditoria: "senha alterada em".
ALTER TABLE usuario ADD COLUMN senha_alterada_em TIMESTAMP;
