-- Questionários pré-consulta.
--
-- O paciente responde por link, sem conta — o mesmo mecanismo pelo qual ele lê
-- o plano. É recurso de tempo do nutricionista, e não de engajamento do
-- paciente: chegar à consulta com a leitura feita é o que ele compra aqui.
--
-- Duas redundâncias deliberadas sustentam o modelo, e as duas existem porque
-- uma resposta é o registro de uma consulta que aconteceu numa data:
--
--   1. A resposta guarda o enunciado da pergunta, e não só a chave dela. Se o
--      nutricionista remover uma pergunta do modelo depois, a resposta antiga
--      não pode perder o enunciado — o paciente respondeu àquela pergunta.
--   2. A resposta guarda a versão do modelo que foi aplicada. É o que permite
--      saber qual formulário o paciente viu, sem reconstruí-lo.
--
-- Sobre instrumentos validados: o sistema traz um modelo genérico de
-- pré-consulta, de autoria própria. Instrumentos publicados — rastreamento
-- metabólico, FINDRISC, escalas de sono — têm licença própria, e cabe a cada
-- consultório cadastrar os que tem direito de usar.

CREATE TABLE questionario (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Nulo identifica modelo do sistema, comum a todos os consultórios.
    conta_id       BIGINT,
    nome           VARCHAR(150) NOT NULL,
    descricao      VARCHAR(1000),
    -- Nome do instrumento publicado, quando o questionário for um deles.
    instrumento    VARCHAR(120),
    versao         VARCHAR(30),
    pontuavel      BOOLEAN      NOT NULL DEFAULT FALSE,
    -- Faixas de corte, no formato "0-5=Baixo|6-10=Moderado|11-99=Alto".
    faixa_de_corte VARCHAR(500),
    -- Incrementa a cada edição. A resposta guarda o número que respondeu.
    versao_modelo  INTEGER      NOT NULL DEFAULT 1,
    ativo          BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em      TIMESTAMP    NOT NULL,
    atualizado_em  TIMESTAMP,
    criado_por     VARCHAR(180),
    atualizado_por VARCHAR(180),
    CONSTRAINT fk_questionario_conta FOREIGN KEY (conta_id) REFERENCES conta (id)
);

CREATE INDEX ix_questionario_conta ON questionario (conta_id);

CREATE TABLE pergunta (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    questionario_id  BIGINT       NOT NULL,
    enunciado        VARCHAR(500) NOT NULL,
    -- TEXTO | NUMERO | ESCOLHA_UNICA | MULTIPLA
    tipo             VARCHAR(20)  NOT NULL,
    obrigatoria      BOOLEAN      NOT NULL DEFAULT FALSE,
    ordem            INTEGER      NOT NULL,
    -- Opções no formato "Nunca=0|Às vezes=1|Sempre=2". O número depois do sinal
    -- é a pontuação, e fica ausente quando o questionário não pontua.
    opcoes           VARCHAR(2000),
    ajuda            VARCHAR(500),
    criado_em        TIMESTAMP    NOT NULL,
    atualizado_em    TIMESTAMP,
    criado_por       VARCHAR(180),
    atualizado_por   VARCHAR(180),
    CONSTRAINT fk_pergunta_questionario FOREIGN KEY (questionario_id)
        REFERENCES questionario (id)
);

CREATE INDEX ix_pergunta_questionario ON pergunta (questionario_id);

CREATE TABLE resposta_questionario (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conta_id              BIGINT       NOT NULL,
    paciente_id           BIGINT       NOT NULL,
    agendamento_id        BIGINT,
    questionario_id       BIGINT       NOT NULL,
    -- A versão do modelo que o paciente viu.
    versao_modelo         INTEGER      NOT NULL,
    -- Endereço do formulário, como o identificador do plano público.
    identificador_publico VARCHAR(36)  NOT NULL,
    enviado_em            TIMESTAMP    NOT NULL,
    respondido_em         TIMESTAMP,
    escore                INTEGER,
    classificacao         VARCHAR(120),
    -- A regra de corte usada, congelada na resposta.
    faixa_de_corte        VARCHAR(500),
    criado_em             TIMESTAMP    NOT NULL,
    atualizado_em         TIMESTAMP,
    criado_por            VARCHAR(180),
    atualizado_por        VARCHAR(180),
    CONSTRAINT fk_resposta_conta         FOREIGN KEY (conta_id)        REFERENCES conta (id),
    CONSTRAINT fk_resposta_paciente      FOREIGN KEY (paciente_id)     REFERENCES paciente (id),
    CONSTRAINT fk_resposta_agendamento   FOREIGN KEY (agendamento_id)  REFERENCES agendamento (id),
    CONSTRAINT fk_resposta_questionario  FOREIGN KEY (questionario_id) REFERENCES questionario (id),
    CONSTRAINT uk_resposta_publica UNIQUE (identificador_publico)
);

CREATE INDEX ix_resposta_paciente ON resposta_questionario (paciente_id);
CREATE INDEX ix_resposta_publica  ON resposta_questionario (identificador_publico);

CREATE TABLE resposta_item (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resposta_id     BIGINT       NOT NULL,
    pergunta_id     BIGINT,
    -- Congelado no envio: a pergunta pode sair do modelo depois.
    pergunta_texto  VARCHAR(500) NOT NULL,
    valor           VARCHAR(2000),
    pontos          INTEGER,
    ordem           INTEGER      NOT NULL,
    criado_em       TIMESTAMP    NOT NULL,
    atualizado_em   TIMESTAMP,
    criado_por      VARCHAR(180),
    atualizado_por  VARCHAR(180),
    CONSTRAINT fk_item_resposta FOREIGN KEY (resposta_id) REFERENCES resposta_questionario (id)
);

CREATE INDEX ix_item_resposta ON resposta_item (resposta_id);

-- ---------------------------------------------------------------------------
-- Modelo genérico de pré-consulta, de autoria própria. Serve de ponto de
-- partida editável; instrumentos publicados ficam a cargo de cada consultório.
-- ---------------------------------------------------------------------------

INSERT INTO questionario (conta_id, nome, descricao, pontuavel, versao_modelo, ativo, criado_em)
VALUES (NULL, 'Pré-consulta',
        'Enviado antes da primeira consulta. Chega respondido, e a consulta começa da análise.',
        FALSE, 1, TRUE, CURRENT_TIMESTAMP);

INSERT INTO pergunta (questionario_id, enunciado, tipo, obrigatoria, ordem, opcoes, ajuda, criado_em)
SELECT q.id, p.enunciado, p.tipo, p.obrigatoria, p.ordem, p.opcoes, p.ajuda, CURRENT_TIMESTAMP
FROM questionario q
JOIN (
    SELECT 'O que você espera do acompanhamento nutricional?' AS enunciado,
           'TEXTO' AS tipo, TRUE AS obrigatoria, 1 AS ordem,
           CAST(NULL AS VARCHAR(2000)) AS opcoes,
           CAST('Escreva com suas palavras.' AS VARCHAR(500)) AS ajuda
    UNION ALL SELECT 'Você tem alguma condição de saúde diagnosticada?', 'TEXTO', FALSE, 2,
           NULL, 'Diabetes, hipertensão, tireoide, doença celíaca, outras.'
    UNION ALL SELECT 'Faz uso de medicamento ou suplemento?', 'TEXTO', FALSE, 3,
           NULL, 'Inclua a dose, se souber.'
    UNION ALL SELECT 'Tem alergia ou intolerância alimentar?', 'TEXTO', FALSE, 4, NULL, NULL
    UNION ALL SELECT 'Quantas refeições você faz por dia?', 'ESCOLHA_UNICA', TRUE, 5,
           'Uma ou duas|Três|Quatro ou cinco|Mais de cinco', NULL
    UNION ALL SELECT 'Com que frequência come fora de casa?', 'ESCOLHA_UNICA', FALSE, 6,
           'Raramente|Uma ou duas vezes por semana|Quase todo dia|Todo dia', NULL
    UNION ALL SELECT 'Quantos litros de água você bebe por dia?', 'NUMERO', FALSE, 7, NULL, NULL
    UNION ALL SELECT 'Pratica atividade física?', 'ESCOLHA_UNICA', FALSE, 8,
           'Não pratico|Uma a duas vezes por semana|Três a quatro vezes|Cinco ou mais', NULL
    UNION ALL SELECT 'Quantas horas você dorme por noite?', 'NUMERO', FALSE, 9, NULL, NULL
    UNION ALL SELECT 'Há algo que você gostaria que eu soubesse antes da consulta?', 'TEXTO',
           FALSE, 10, NULL, NULL
) p ON TRUE
WHERE q.conta_id IS NULL AND q.nome = 'Pré-consulta';
