-- Fundacao: tenant (conta) e usuarios.
-- SQL mantido em subconjunto portavel entre H2 (MODE=PostgreSQL) e PostgreSQL.

CREATE TABLE conta (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR(150) NOT NULL,
    plano           VARCHAR(20)  NOT NULL,
    plano_expira_em DATE,
    cor_primaria    VARCHAR(7),
    logo_url        VARCHAR(500),
    ativa           BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em       TIMESTAMP    NOT NULL,
    atualizado_em   TIMESTAMP,
    criado_por      VARCHAR(180),
    atualizado_por  VARCHAR(180)
);

CREATE TABLE usuario (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome           VARCHAR(150) NOT NULL,
    email          VARCHAR(180) NOT NULL,
    senha_hash     VARCHAR(100) NOT NULL,
    perfil         VARCHAR(20)  NOT NULL,
    conta_id       BIGINT       NOT NULL,
    crn            VARCHAR(30),
    telefone       VARCHAR(20),
    ativo          BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em      TIMESTAMP    NOT NULL,
    atualizado_em  TIMESTAMP,
    criado_por     VARCHAR(180),
    atualizado_por VARCHAR(180),
    CONSTRAINT uk_usuario_email UNIQUE (email),
    CONSTRAINT fk_usuario_conta FOREIGN KEY (conta_id) REFERENCES conta (id)
);

CREATE INDEX ix_usuario_conta ON usuario (conta_id);
