-- Anamnese geral.
--
-- O cliente chama esta área de coração do atendimento, e ela não existia. São
-- duas coisas no mesmo registro, e elas têm naturezas diferentes:
--
--   1. O corpo, em texto rico. É a conversa da consulta, escrita como o
--      nutricionista quiser. Fica no formato do editor, validado na entrada
--      por RichTextDocument.
--   2. Os campos de destaque, que ele pediu depois de ler a proposta de um
--      campo só: "pontos em que eu iria colocar as informações que eu queria
--      que aparecessem lá". São rótulo e valor curto — Objetivo, Propósito da
--      consulta — e é o que aparece na listagem sem abrir a anamnese.
--
-- Resumir o texto livre automaticamente resolveria o mesmo problema por
-- adivinhação. O campo declarado diz o que ele quis dizer, e não o que um
-- resumidor achou que ele quis.
--
-- A redundância do rótulo em anamnesis_value é deliberada, pelo mesmo motivo
-- que resposta_item guarda o enunciado da pergunta: se ele renomear o campo
-- "Objetivo" para "Meta" no ano que vem, a anamnese do ano passado continua
-- dizendo o que dizia. Registro clínico é registro de uma data.
--
-- Só usa o subconjunto comum a H2 e PostgreSQL (AD-11).

-- ---------------------------------------------------------------- os campos

CREATE TABLE anamnesis_field (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id      BIGINT       NOT NULL,
    label           VARCHAR(120) NOT NULL,
    sort_order      INTEGER      NOT NULL,
    -- Se o valor aparece na listagem de anamneses do paciente.
    show_in_listing BOOLEAN      NOT NULL DEFAULT TRUE,
    active          BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP    NOT NULL,
    updated_at      TIMESTAMP,
    created_by      VARCHAR(180),
    updated_by      VARCHAR(180),
    CONSTRAINT fk_anamnesis_field_account FOREIGN KEY (account_id) REFERENCES account (id)
);

CREATE INDEX ix_anamnesis_field_account ON anamnesis_field (account_id);

-- --------------------------------------------------------------- a anamnese

CREATE TABLE anamnesis (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id     BIGINT       NOT NULL,
    patient_id     BIGINT       NOT NULL,
    -- Nome do arquivo, dado pelo nutricionista. Aparece na listagem.
    name           VARCHAR(150) NOT NULL,
    date           DATE         NOT NULL,
    -- Documento do editor, em JSON. Nulo enquanto estiver em branco.
    -- O JSON do ProseMirror gasta algumas vezes o tamanho do texto que carrega,
    -- então o limite é folgado em relação ao VARCHAR(8000) das orientações.
    body           VARCHAR(40000),
    created_at     TIMESTAMP    NOT NULL,
    updated_at     TIMESTAMP,
    created_by     VARCHAR(180),
    updated_by     VARCHAR(180),
    CONSTRAINT fk_anamnesis_account FOREIGN KEY (account_id) REFERENCES account (id),
    CONSTRAINT fk_anamnesis_patient FOREIGN KEY (patient_id) REFERENCES patient (id)
);

CREATE INDEX ix_anamnesis_patient ON anamnesis (patient_id);
CREATE INDEX ix_anamnesis_account ON anamnesis (account_id);

-- ------------------------------------------------------ os valores gravados

CREATE TABLE anamnesis_value (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anamnesis_id   BIGINT       NOT NULL,
    -- Nulo quando o campo foi removido do consultório depois desta anamnese.
    field_id       BIGINT,
    -- Congelado no preenchimento: o campo pode ser renomeado depois.
    label          VARCHAR(120) NOT NULL,
    -- "value" é palavra reservada no H2; daí o nome da coluna divergir do campo.
    content        VARCHAR(500),
    sort_order     INTEGER      NOT NULL,
    created_at     TIMESTAMP    NOT NULL,
    updated_at     TIMESTAMP,
    created_by     VARCHAR(180),
    updated_by     VARCHAR(180),
    CONSTRAINT fk_anamnesis_value_anamnesis FOREIGN KEY (anamnesis_id)
        REFERENCES anamnesis (id),
    CONSTRAINT fk_anamnesis_value_field FOREIGN KEY (field_id)
        REFERENCES anamnesis_field (id)
);

CREATE INDEX ix_anamnesis_value_anamnesis ON anamnesis_value (anamnesis_id);
