-- Cálculo energético como área própria.
--
-- Antes eram colunas dentro da avaliação antropométrica: equação, fator de
-- atividade e os dois gastos. Isso impedia três coisas que o cliente pediu —
-- ter histórico de cálculos para a mesma medição, calcular sem medir, e
-- guardar fator de injúria, calorias por MET e programação de peso.
--
-- As colunas antigas continuam onde estão. Avaliações já gravadas as usam, e
-- migrar dado clínico para um módulo novo sem ninguém conferir seria pior do
-- que conviver com a duplicação por um tempo.
--
-- Tudo o que entra na conta é copiado para dentro do registro: peso, altura,
-- idade, sexo e nível de atividade. Eles vêm da antropometria, que muda a cada
-- consulta. Um plano que os lesse ao vivo responderia outro número no mês que
-- vem e continuaria parecendo a mesma prescrição.
--
-- Só usa o subconjunto comum a H2 e PostgreSQL (AD-11).

CREATE TABLE energy_plan (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id       BIGINT       NOT NULL,
    patient_id       BIGINT       NOT NULL,
    name             VARCHAR(150) NOT NULL,
    date             DATE         NOT NULL,
    -- A avaliação de onde vieram as medidas, quando houve uma.
    assessment_id    BIGINT,

    -- entradas, congeladas
    weight_kg        DECIMAL(6,2) NOT NULL,
    height_cm        DECIMAL(6,2) NOT NULL,
    age_years        INTEGER      NOT NULL,
    sex              VARCHAR(20)  NOT NULL,
    -- INACTIVE | LOW_ACTIVE | ACTIVE | VERY_ACTIVE
    activity_level   VARCHAR(20)  NOT NULL,
    injury_factor    DECIMAL(4,2) NOT NULL DEFAULT 1.00,
    met_kcal         DECIMAL(8,2),

    -- programação de peso, pelo Valor Energético do Tecido Adiposo
    target_weight_kg DECIMAL(6,2),
    target_date      DATE,
    -- Negativo para perda. Congelado porque a data-alvo passa.
    adjustment_kcal  DECIMAL(8,2),

    -- resultados
    average_kcal     DECIMAL(8,2) NOT NULL,
    prescribed_kcal  DECIMAL(8,2) NOT NULL,

    notes            VARCHAR(2000),
    created_at       TIMESTAMP    NOT NULL,
    updated_at       TIMESTAMP,
    created_by       VARCHAR(180),
    updated_by       VARCHAR(180),
    CONSTRAINT fk_energy_plan_account    FOREIGN KEY (account_id)    REFERENCES account (id),
    CONSTRAINT fk_energy_plan_patient    FOREIGN KEY (patient_id)    REFERENCES patient (id),
    CONSTRAINT fk_energy_plan_assessment FOREIGN KEY (assessment_id)
        REFERENCES anthropometric_assessment (id)
);

CREATE INDEX ix_energy_plan_patient ON energy_plan (patient_id);
CREATE INDEX ix_energy_plan_account ON energy_plan (account_id);

-- Uma linha por equação selecionada. É o que permite a média que ele pediu:
-- "gostaria de poder fazer a média da EER 2023 com a de 2005".
CREATE TABLE energy_plan_equation (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id        BIGINT       NOT NULL,
    -- HARRIS_BENEDICT_1984 | MIFFLIN_ST_JEOR | FAO_WHO_2004 | EER_IOM_2005 | EER_2023
    equation       VARCHAR(40)  NOT NULL,
    -- Nulo para equação que já responde o gasto do dia inteiro.
    basal_kcal     DECIMAL(8,2),
    total_kcal     DECIMAL(8,2) NOT NULL,
    sort_order     INTEGER      NOT NULL,
    created_at     TIMESTAMP    NOT NULL,
    updated_at     TIMESTAMP,
    created_by     VARCHAR(180),
    updated_by     VARCHAR(180),
    CONSTRAINT fk_energy_equation_plan FOREIGN KEY (plan_id) REFERENCES energy_plan (id)
);

CREATE INDEX ix_energy_equation_plan ON energy_plan_equation (plan_id);
