-- Antropometria completa.
--
-- O cliente lista treze locais de circunferência, sete deles medidos dos dois
-- lados (pp. 22–23). Em colunas isso seriam vinte campos numa tabela que já
-- tinha dezessete, e o décimo quarto local pediria outra migração. Por isso as
-- circunferências saem para uma tabela própria, com local e lado.
--
-- As dobras cutâneas continuam em coluna, de propósito: são um conjunto
-- fechado de dez, nenhuma tem lado, e os protocolos de composição as leem por
-- nome. Normalizar também as dobras trocaria código que funciona por código
-- equivalente, sem ganhar nada.
--
-- Diâmetros ósseos e bioimpedância entram como coluna pelo mesmo motivo:
-- conjunto fixo, sem lado.
--
-- Sobre a conversão do que já existia: `arm` vira ARM_RELAXED e `thigh` vira
-- THIGH_MEDIAL, que são os locais padrão quando ninguém qualifica. O lado fica
-- SINGLE — a medida antiga não registrou qual braço era, e escolher um agora
-- seria inventar um dado que ninguém observou.
--
-- Só usa o subconjunto comum a H2 e PostgreSQL (AD-11).

CREATE TABLE assessment_circumference (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id BIGINT       NOT NULL,
    -- NECK | SHOULDER | CHEST | WAIST | ABDOMEN | HIP | ARM_RELAXED |
    -- ARM_CONTRACTED | FOREARM | THIGH_PROXIMAL | THIGH_MEDIAL |
    -- THIGH_DISTAL | CALF
    site          VARCHAR(30)  NOT NULL,
    -- SINGLE | RIGHT | LEFT
    side          VARCHAR(10)  NOT NULL DEFAULT 'SINGLE',
    value_cm      DECIMAL(6,2) NOT NULL,
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP,
    created_by    VARCHAR(180),
    updated_by    VARCHAR(180),
    CONSTRAINT fk_circumference_assessment FOREIGN KEY (assessment_id)
        REFERENCES anthropometric_assessment (id),
    CONSTRAINT uk_circumference_site UNIQUE (assessment_id, site, side)
);

CREATE INDEX ix_circumference_assessment ON assessment_circumference (assessment_id);

-- ------------------------------------------------- o que já estava em coluna

INSERT INTO assessment_circumference (assessment_id, site, side, value_cm, created_at)
SELECT id, 'WAIST', 'SINGLE', waist_circumference, CURRENT_TIMESTAMP
FROM anthropometric_assessment WHERE waist_circumference IS NOT NULL;

INSERT INTO assessment_circumference (assessment_id, site, side, value_cm, created_at)
SELECT id, 'HIP', 'SINGLE', hip_circumference, CURRENT_TIMESTAMP
FROM anthropometric_assessment WHERE hip_circumference IS NOT NULL;

INSERT INTO assessment_circumference (assessment_id, site, side, value_cm, created_at)
SELECT id, 'ABDOMEN', 'SINGLE', abdomen_circumference, CURRENT_TIMESTAMP
FROM anthropometric_assessment WHERE abdomen_circumference IS NOT NULL;

INSERT INTO assessment_circumference (assessment_id, site, side, value_cm, created_at)
SELECT id, 'CHEST', 'SINGLE', chest_circumference, CURRENT_TIMESTAMP
FROM anthropometric_assessment WHERE chest_circumference IS NOT NULL;

INSERT INTO assessment_circumference (assessment_id, site, side, value_cm, created_at)
SELECT id, 'ARM_RELAXED', 'SINGLE', arm_circumference, CURRENT_TIMESTAMP
FROM anthropometric_assessment WHERE arm_circumference IS NOT NULL;

INSERT INTO assessment_circumference (assessment_id, site, side, value_cm, created_at)
SELECT id, 'FOREARM', 'SINGLE', forearm_circumference, CURRENT_TIMESTAMP
FROM anthropometric_assessment WHERE forearm_circumference IS NOT NULL;

INSERT INTO assessment_circumference (assessment_id, site, side, value_cm, created_at)
SELECT id, 'THIGH_MEDIAL', 'SINGLE', thigh_circumference, CURRENT_TIMESTAMP
FROM anthropometric_assessment WHERE thigh_circumference IS NOT NULL;

INSERT INTO assessment_circumference (assessment_id, site, side, value_cm, created_at)
SELECT id, 'CALF', 'SINGLE', calf_circumference, CURRENT_TIMESTAMP
FROM anthropometric_assessment WHERE calf_circumference IS NOT NULL;

ALTER TABLE anthropometric_assessment DROP COLUMN waist_circumference;
ALTER TABLE anthropometric_assessment DROP COLUMN hip_circumference;
ALTER TABLE anthropometric_assessment DROP COLUMN abdomen_circumference;
ALTER TABLE anthropometric_assessment DROP COLUMN chest_circumference;
ALTER TABLE anthropometric_assessment DROP COLUMN arm_circumference;
ALTER TABLE anthropometric_assessment DROP COLUMN forearm_circumference;
ALTER TABLE anthropometric_assessment DROP COLUMN thigh_circumference;
ALTER TABLE anthropometric_assessment DROP COLUMN calf_circumference;

-- ------------------------------------------------------------ dobra que faltava

-- Supraespinhal, listada pelo cliente na página 22.
ALTER TABLE anthropometric_assessment ADD COLUMN supraspinal_skinfold DECIMAL(6,2);

-- ------------------------------------------------------------ alturas de apoio

ALTER TABLE anthropometric_assessment ADD COLUMN sitting_height_cm DECIMAL(6,2);
ALTER TABLE anthropometric_assessment ADD COLUMN knee_height_cm DECIMAL(6,2);

-- ---------------------------------------------------------- diâmetros ósseos

ALTER TABLE anthropometric_assessment ADD COLUMN humerus_diameter_cm DECIMAL(6,2);
ALTER TABLE anthropometric_assessment ADD COLUMN wrist_diameter_cm   DECIMAL(6,2);
ALTER TABLE anthropometric_assessment ADD COLUMN femur_diameter_cm   DECIMAL(6,2);

-- ------------------------------------------------------------- bioimpedância
--
-- Vem da balança, não de conta. Por isso são campos digitados e não derivados:
-- se o aparelho diz 22,4% de gordura, é isso que fica registrado, e não um
-- número que o sistema recalculou por outro caminho.

ALTER TABLE anthropometric_assessment ADD COLUMN bia_fat_percentage  DECIMAL(5,2);
ALTER TABLE anthropometric_assessment ADD COLUMN bia_fat_mass_kg     DECIMAL(6,2);
ALTER TABLE anthropometric_assessment ADD COLUMN bia_muscle_percentage DECIMAL(5,2);
ALTER TABLE anthropometric_assessment ADD COLUMN bia_muscle_mass_kg  DECIMAL(6,2);
ALTER TABLE anthropometric_assessment ADD COLUMN bia_lean_mass_kg    DECIMAL(6,2);
ALTER TABLE anthropometric_assessment ADD COLUMN bia_bone_mass_kg    DECIMAL(6,2);
ALTER TABLE anthropometric_assessment ADD COLUMN bia_visceral_fat    DECIMAL(5,2);
ALTER TABLE anthropometric_assessment ADD COLUMN bia_body_water_percentage DECIMAL(5,2);
ALTER TABLE anthropometric_assessment ADD COLUMN bia_metabolic_age   INTEGER;
