-- O perfil do paciente, das páginas 1, 3 e 4 do documento.
--
-- Quatro coisas, e cada uma responde a um pedido:
--
--   1. TAGs. "A TAG do paciente deverá funcionar como um aglutinador dos
--      pacientes, tendo algumas opções já disponíveis, como p. ex.,
--      HIPERTROFIA, EMAGRECIMENTO, DIABÉTICO, CELÍACO". Conta nula identifica
--      as que o sistema traz; o consultório cria as suas.
--
--      É a TAG que resolve o que ele queria do avatar colorido — varrer a lista
--      sem ler nome. Duas cores por sexo dão dois grupos; TAG dá quantos ele
--      criar.
--
--   2. Apelido e condição biológica, que ele lista como opcionais do cadastro.
--      A condição só se aplica a mulher, e por isso aceita nulo em vez de ter
--      um valor "não se aplica" que apareceria para todo mundo.
--
--   3. Anotações em feed. "anotações do nutricionista sobre o paciente p. ex.,
--      o nutricionista se sentiu ofendido com algo que o paciente fez ou
--      falou... como se fosse um tweet sabe?" São datadas e sucessivas, então
--      não cabem no campo único de observações que já existe — esse continua
--      sendo a descrição do paciente, e não o diário.
--
-- Só usa o subconjunto comum a H2 e PostgreSQL (AD-11).

ALTER TABLE patient ADD COLUMN nickname VARCHAR(80);

-- PREGNANT | LACTATING. Nulo para quem não está em nenhuma das duas.
ALTER TABLE patient ADD COLUMN biological_condition VARCHAR(20);

-- ------------------------------------------------------------------- as TAGs

CREATE TABLE patient_tag (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Nulo identifica TAG do sistema, comum a todos os consultórios.
    account_id BIGINT,
    name       VARCHAR(40) NOT NULL,
    active     BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP   NOT NULL,
    updated_at TIMESTAMP,
    created_by VARCHAR(180),
    updated_by VARCHAR(180),
    CONSTRAINT fk_patient_tag_account FOREIGN KEY (account_id) REFERENCES account (id)
);

CREATE INDEX ix_patient_tag_account ON patient_tag (account_id);

CREATE TABLE patient_tag_link (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    tag_id     BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    created_by VARCHAR(180),
    updated_by VARCHAR(180),
    CONSTRAINT fk_tag_link_patient FOREIGN KEY (patient_id) REFERENCES patient (id),
    CONSTRAINT fk_tag_link_tag     FOREIGN KEY (tag_id)     REFERENCES patient_tag (id),
    CONSTRAINT uk_tag_link UNIQUE (patient_id, tag_id)
);

CREATE INDEX ix_tag_link_patient ON patient_tag_link (patient_id);

-- As que ele cita no documento, como ponto de partida.
INSERT INTO patient_tag (account_id, name, active, created_at) VALUES
    (NULL, 'HIPERTROFIA',    TRUE, CURRENT_TIMESTAMP),
    (NULL, 'EMAGRECIMENTO',  TRUE, CURRENT_TIMESTAMP),
    (NULL, 'DIABÉTICO',      TRUE, CURRENT_TIMESTAMP),
    (NULL, 'CELÍACO',        TRUE, CURRENT_TIMESTAMP),
    (NULL, 'HIPERTENSO',     TRUE, CURRENT_TIMESTAMP),
    (NULL, 'ESPORTISTA',     TRUE, CURRENT_TIMESTAMP),
    (NULL, 'VEGETARIANO',    TRUE, CURRENT_TIMESTAMP),
    (NULL, 'GESTANTE',       TRUE, CURRENT_TIMESTAMP);

-- -------------------------------------------------------- anotações em feed

CREATE TABLE patient_note (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT        NOT NULL,
    patient_id BIGINT        NOT NULL,
    body       VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP     NOT NULL,
    updated_at TIMESTAMP,
    created_by VARCHAR(180),
    updated_by VARCHAR(180),
    CONSTRAINT fk_patient_note_account FOREIGN KEY (account_id) REFERENCES account (id),
    CONSTRAINT fk_patient_note_patient FOREIGN KEY (patient_id) REFERENCES patient (id)
);

CREATE INDEX ix_patient_note_patient ON patient_note (patient_id, created_at);
