CREATE TABLE paciente (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conta_id         BIGINT       NOT NULL,
    nome             VARCHAR(150) NOT NULL,
    email            VARCHAR(180),
    telefone         VARCHAR(20),
    data_nascimento  DATE,
    sexo             VARCHAR(10),
    cpf              VARCHAR(20),
    profissao        VARCHAR(100),
    objetivo         VARCHAR(500),
    observacoes      VARCHAR(2000),
    usuario_id       BIGINT,
    ativo            BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em        TIMESTAMP    NOT NULL,
    atualizado_em    TIMESTAMP,
    criado_por       VARCHAR(180),
    atualizado_por   VARCHAR(180),
    CONSTRAINT fk_paciente_conta   FOREIGN KEY (conta_id)   REFERENCES conta (id),
    CONSTRAINT fk_paciente_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id)
);

CREATE INDEX ix_paciente_conta      ON paciente (conta_id);
CREATE INDEX ix_paciente_conta_nome ON paciente (conta_id, nome);
