-- Arquivos anexos do paciente.
--
-- Estava na lista de áreas dele (página 2) e não existia nada genérico — só
-- anexo de laudo dentro de exames.
--
-- É também a resposta concreta à dúvida dele sobre migração: "teria de
-- qualquer forma de ter o trabalho de mandar os meus comentários, receitas,
-- alimentos, pacientes... para lá. Se possível, para mandar os cardápios para
-- eu não ter que fazer um a um, poderia deixar uma maneira de eu enviar o PDF,
-- ou de eu salvar o link de acesso dele em algum canto... Não entendo bem do
-- que fazer em relação aos pacientes ativos".
--
-- Com isto ele não recria cardápio antigo: anexa o PDF do Webdiet ao paciente,
-- o histórico fica junto do prontuário, e o próximo planejamento de cada um
-- nasce aqui. A virada acontece paciente a paciente, na consulta seguinte de
-- cada um, sem data de corte.
--
-- Arquivo e link na mesma tabela de propósito: para quem usa, são a mesma
-- coisa — algo do paciente que fica guardado. Separar em duas telas obrigaria
-- a saber de antemão em qual procurar.
--
-- Só usa o subconjunto comum a H2 e PostgreSQL (AD-11).

CREATE TABLE patient_attachment (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id   BIGINT       NOT NULL,
    patient_id   BIGINT       NOT NULL,
    title        VARCHAR(150) NOT NULL,
    -- FILE | LINK
    kind         VARCHAR(10)  NOT NULL,
    -- Preenchidos quando é arquivo.
    file_name    VARCHAR(200),
    file_type    VARCHAR(100),
    file_size    BIGINT,
    -- Preenchido quando é link.
    url          VARCHAR(2000),
    notes        VARCHAR(1000),
    -- A data do documento, que raramente é a data em que ele foi anexado.
    reference_date DATE,
    created_at   TIMESTAMP    NOT NULL,
    updated_at   TIMESTAMP,
    created_by   VARCHAR(180),
    updated_by   VARCHAR(180),
    CONSTRAINT fk_attachment_account FOREIGN KEY (account_id) REFERENCES account (id),
    CONSTRAINT fk_attachment_patient FOREIGN KEY (patient_id) REFERENCES patient (id),
    -- A invariante escrita onde não dá para esquecer: arquivo tem nome, link
    -- tem endereço, e nenhum dos dois é as duas coisas.
    CONSTRAINT ck_attachment_kind CHECK (
        (kind = 'FILE' AND file_name IS NOT NULL)
        OR (kind = 'LINK' AND url IS NOT NULL)
    )
);

CREATE INDEX ix_attachment_patient ON patient_attachment (patient_id, reference_date);

CREATE TABLE patient_attachment_content (
    attachment_id BIGINT NOT NULL PRIMARY KEY,
    content       BYTEA  NOT NULL,
    created_at    TIMESTAMP NOT NULL,
    updated_at    TIMESTAMP,
    created_by    VARCHAR(180),
    updated_by    VARCHAR(180),
    CONSTRAINT fk_attachment_content FOREIGN KEY (attachment_id)
        REFERENCES patient_attachment (id)
);
