-- Modelos de anotacao do nutricionista.
--
-- "Eu tenho que ter a possibilidade de salvar modelos, e adicionar ele no
-- bloco de anotacoes para um paciente hipotetico, e com a MESMA FORMATACAO do
-- cadastro." O bloco de anotacoes ja e texto formatado; o que faltava era
-- guardar um texto-base (primeira consulta, retorno) e comeca-lo de novo em
-- qualquer paciente sem perder negrito, lista e tabela.
--
-- O modelo e do consultorio, nao do paciente: por isso nao tem patient_id.
-- O corpo e o mesmo documento JSON do editor, no mesmo tamanho da anotacao.
--
-- So usa o subconjunto comum a H2 e PostgreSQL (AD-11).

CREATE TABLE note_template (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT        NOT NULL,
    name       VARCHAR(120)  NOT NULL,
    body       VARCHAR(8000) NOT NULL,
    created_at TIMESTAMP     NOT NULL,
    updated_at TIMESTAMP,
    created_by VARCHAR(180),
    updated_by VARCHAR(180),
    CONSTRAINT fk_note_template_account FOREIGN KEY (account_id) REFERENCES account (id)
);

CREATE INDEX ix_note_template_account ON note_template (account_id, name);
