-- Parceiros de indicacao, pacotes de trabalho e parcelamento no financeiro.
--
-- "Eu quero um registro de parceiros. P. ex., se eu aumentar muito o volume
-- de pacientes por indicacao, eu quero vincular a consulta/agendamento a um
-- parceiro cadastrado, para eventuais beneficios ao indicante."
--
-- "Quero poder tambem registrar os meus pacotes de trabalho. Para quando
-- agendar ja selecionar o que eu cadastrei anteriormente." Um pacote e um
-- nome atrelado a um valor; se tiver numero de encontros, a agenda pode marcar
-- as proximas consultas no intervalo combinado.
--
-- O parceiro fica no paciente (quem o indicou) e pode ficar tambem na
-- consulta (quando a indicacao vale para aquele atendimento). O pacote fica
-- na consulta e no lancamento, para o relatorio financeiro dizer quanto cada
-- pacote rendeu.
--
-- Parcelas: n lancamentos com o mesmo grupo, numerados. O numero do documento
-- e o recibo/nota que o consultorio emite fora do sistema.
--
-- So usa o subconjunto comum a H2 e PostgreSQL (AD-11).

CREATE TABLE partner (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT        NOT NULL,
    name       VARCHAR(150)  NOT NULL,
    kind       VARCHAR(40),
    contact    VARCHAR(180),
    notes      VARCHAR(1000),
    active     BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP     NOT NULL,
    updated_at TIMESTAMP,
    created_by VARCHAR(180),
    updated_by VARCHAR(180),
    CONSTRAINT fk_partner_account FOREIGN KEY (account_id) REFERENCES account (id)
);

CREATE INDEX ix_partner_account ON partner (account_id, name);

CREATE TABLE service_package (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id    BIGINT         NOT NULL,
    name          VARCHAR(120)   NOT NULL,
    amount        DECIMAL(12, 2) NOT NULL,
    sessions      INTEGER,
    interval_days INTEGER,
    notes         VARCHAR(500),
    active        BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP      NOT NULL,
    updated_at    TIMESTAMP,
    created_by    VARCHAR(180),
    updated_by    VARCHAR(180),
    CONSTRAINT fk_service_package_account FOREIGN KEY (account_id) REFERENCES account (id)
);

CREATE INDEX ix_service_package_account ON service_package (account_id, name);

ALTER TABLE patient ADD COLUMN partner_id BIGINT;
ALTER TABLE patient ADD CONSTRAINT fk_patient_partner
    FOREIGN KEY (partner_id) REFERENCES partner (id);

ALTER TABLE appointment ADD COLUMN partner_id BIGINT;
ALTER TABLE appointment ADD COLUMN package_id BIGINT;
ALTER TABLE appointment ADD CONSTRAINT fk_appointment_partner
    FOREIGN KEY (partner_id) REFERENCES partner (id);
ALTER TABLE appointment ADD CONSTRAINT fk_appointment_package
    FOREIGN KEY (package_id) REFERENCES service_package (id);

ALTER TABLE finance_transaction ADD COLUMN document_number    VARCHAR(60);
ALTER TABLE finance_transaction ADD COLUMN installment_group  VARCHAR(36);
ALTER TABLE finance_transaction ADD COLUMN installment_index  INTEGER;
ALTER TABLE finance_transaction ADD COLUMN installment_count  INTEGER;
ALTER TABLE finance_transaction ADD COLUMN package_id         BIGINT;
ALTER TABLE finance_transaction ADD CONSTRAINT fk_transaction_package
    FOREIGN KEY (package_id) REFERENCES service_package (id);

CREATE INDEX ix_transaction_installment ON finance_transaction (installment_group);
