-- A anamnese construida como questionario.
--
-- O cliente pediu "anamnese programavel (checkbox, resposta curta,
-- paragrafo)", enviada antes da consulta para o paciente responder, e
-- escolheu o construtor de questionarios como o jeito de faze-la. A anamnese
-- passa entao a poder nascer de um questionario: o nutricionista escolhe o
-- modelo, preenche na consulta (ou importa o que o paciente respondeu pelo
-- link) e o registro guarda as respostas, pergunta a pergunta.
--
-- As respostas ficam numa tabela propria, e nao em resposta_item, porque nao
-- sao um envio ao paciente: sao o que o nutricionista escreveu, com a mesma
-- regra das outras — o enunciado e o tipo congelam no preenchimento, porque
-- o modelo pode mudar depois e a anamnese e o registro de uma data.
--
-- O destaque na pergunta e o que a listagem mostra sem abrir a anamnese,
-- como ja fazem os campos de destaque.
--
-- So usa o subconjunto comum a H2 e PostgreSQL (AD-11).

ALTER TABLE question ADD COLUMN highlight BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE anamnesis ADD COLUMN questionnaire_id   BIGINT;
ALTER TABLE anamnesis ADD COLUMN questionnaire_name VARCHAR(150);
ALTER TABLE anamnesis ADD COLUMN template_version   INTEGER;
-- O envio pre-consulta de que esta anamnese foi importada, quando foi.
ALTER TABLE anamnesis ADD COLUMN sending_id         BIGINT;
ALTER TABLE anamnesis ADD CONSTRAINT fk_anamnesis_questionnaire
    FOREIGN KEY (questionnaire_id) REFERENCES questionnaire (id);
ALTER TABLE anamnesis ADD CONSTRAINT fk_anamnesis_sending
    FOREIGN KEY (sending_id) REFERENCES questionnaire_answer (id);

CREATE TABLE anamnesis_answer (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anamnesis_id   BIGINT        NOT NULL,
    -- Nulo quando a pergunta saiu do modelo depois desta anamnese.
    question_id    BIGINT,
    -- Congelados no preenchimento.
    statement      VARCHAR(500)  NOT NULL,
    question_type  VARCHAR(20)   NOT NULL,
    content        VARCHAR(4000),
    highlight      BOOLEAN       NOT NULL DEFAULT FALSE,
    sort_order     INTEGER       NOT NULL,
    created_at     TIMESTAMP     NOT NULL,
    updated_at     TIMESTAMP,
    created_by     VARCHAR(180),
    updated_by     VARCHAR(180),
    CONSTRAINT fk_anamnesis_answer_anamnesis FOREIGN KEY (anamnesis_id)
        REFERENCES anamnesis (id)
);

CREATE INDEX ix_anamnesis_answer_anamnesis ON anamnesis_answer (anamnesis_id);
