-- Base de alimentos.
--
-- conta_id NULO identifica alimento de base publica (TACO/TBCA/IBGE),
-- visivel para todos os consultorios. Preenchido, o alimento pertence
-- ao consultorio que o cadastrou.

CREATE TABLE alimento (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conta_id        BIGINT,
    descricao       VARCHAR(250) NOT NULL,
    descricao_busca VARCHAR(250) NOT NULL,
    grupo           VARCHAR(100),
    fonte           VARCHAR(20)  NOT NULL,
    codigo_fonte    VARCHAR(30),
    marca           VARCHAR(100),

    umidade_pct     DECIMAL(10,4),
    energia_kcal    DECIMAL(10,4),
    energia_kj      DECIMAL(10,4),
    proteina_g      DECIMAL(10,4),
    lipideos_g      DECIMAL(10,4),
    colesterol_mg   DECIMAL(10,4),
    carboidrato_g   DECIMAL(10,4),
    fibra_g         DECIMAL(10,4),
    cinzas_g        DECIMAL(10,4),
    calcio_mg       DECIMAL(10,4),
    magnesio_mg     DECIMAL(10,4),
    manganes_mg     DECIMAL(10,4),
    fosforo_mg      DECIMAL(10,4),
    ferro_mg        DECIMAL(10,4),
    sodio_mg        DECIMAL(10,4),
    potassio_mg     DECIMAL(10,4),
    cobre_mg        DECIMAL(10,4),
    zinco_mg        DECIMAL(10,4),
    retinol_mcg     DECIMAL(10,4),
    re_mcg          DECIMAL(10,4),
    rae_mcg         DECIMAL(10,4),
    tiamina_mg      DECIMAL(10,4),
    riboflavina_mg  DECIMAL(10,4),
    piridoxina_mg   DECIMAL(10,4),
    niacina_mg      DECIMAL(10,4),
    vitamina_c_mg   DECIMAL(10,4),

    ativo           BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em       TIMESTAMP    NOT NULL,
    atualizado_em   TIMESTAMP,
    criado_por      VARCHAR(180),
    atualizado_por  VARCHAR(180),
    CONSTRAINT fk_alimento_conta FOREIGN KEY (conta_id) REFERENCES conta (id)
);

CREATE INDEX ix_alimento_conta        ON alimento (conta_id);
CREATE INDEX ix_alimento_descricao    ON alimento (descricao_busca);
CREATE INDEX ix_alimento_fonte_codigo ON alimento (fonte, codigo_fonte);

-- Impede importar a mesma tabela duas vezes.
CREATE UNIQUE INDEX uk_alimento_fonte_codigo
    ON alimento (fonte, codigo_fonte);

CREATE TABLE medida_caseira (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alimento_id    BIGINT        NOT NULL,
    descricao      VARCHAR(120)  NOT NULL,
    gramas         DECIMAL(10,3) NOT NULL,
    padrao         BOOLEAN       NOT NULL DEFAULT FALSE,
    criado_em      TIMESTAMP     NOT NULL,
    atualizado_em  TIMESTAMP,
    criado_por     VARCHAR(180),
    atualizado_por VARCHAR(180),
    CONSTRAINT fk_medida_alimento FOREIGN KEY (alimento_id) REFERENCES alimento (id),
    CONSTRAINT ck_medida_gramas CHECK (gramas > 0)
);

CREATE INDEX ix_medida_alimento ON medida_caseira (alimento_id);
