-- Plano alimentar: o nucleo clinico do sistema.
--
-- O plano e uma entidade unica, vista pelo nutricionista e pelo paciente. Nao
-- ha copia por audiencia: o que muda e o caminho de acesso. O paciente abre
-- pelo identificador_publico, um UUID que funciona como endereco do plano —
-- um id sequencial permitiria abrir o plano do vizinho somando 1 ao link.

CREATE TABLE plano_alimentar (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conta_id              BIGINT       NOT NULL,
    paciente_id           BIGINT,
    titulo                VARCHAR(150) NOT NULL,
    metodo                VARCHAR(20)  NOT NULL,
    status                VARCHAR(20)  NOT NULL,
    identificador_publico VARCHAR(36)  NOT NULL,
    vigencia_inicio       DATE,
    vigencia_fim          DATE,
    orientacoes           VARCHAR(4000),
    observacoes_internas  VARCHAR(4000),
    modelo                BOOLEAN      NOT NULL DEFAULT FALSE,
    meta_energia_kcal     DECIMAL(10,2),
    criado_em             TIMESTAMP    NOT NULL,
    atualizado_em         TIMESTAMP,
    criado_por            VARCHAR(180),
    atualizado_por        VARCHAR(180),
    CONSTRAINT fk_plano_conta    FOREIGN KEY (conta_id)    REFERENCES conta (id),
    CONSTRAINT fk_plano_paciente FOREIGN KEY (paciente_id) REFERENCES paciente (id),
    CONSTRAINT uk_plano_publico  UNIQUE (identificador_publico),
    -- Plano de paciente precisa de paciente; modelo, por definicao, nao tem.
    CONSTRAINT ck_plano_modelo CHECK (
        (modelo = TRUE AND paciente_id IS NULL) OR (modelo = FALSE AND paciente_id IS NOT NULL)
    ),
    CONSTRAINT ck_plano_vigencia CHECK (
        vigencia_inicio IS NULL OR vigencia_fim IS NULL OR vigencia_fim >= vigencia_inicio
    )
);

CREATE INDEX ix_plano_conta    ON plano_alimentar (conta_id);
CREATE INDEX ix_plano_paciente ON plano_alimentar (paciente_id);
CREATE INDEX ix_plano_publico  ON plano_alimentar (identificador_publico);

CREATE TABLE refeicao (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plano_id       BIGINT       NOT NULL,
    nome           VARCHAR(100) NOT NULL,
    horario        TIME,
    ordem          INTEGER      NOT NULL,
    observacao     VARCHAR(1000),
    criado_em      TIMESTAMP    NOT NULL,
    atualizado_em  TIMESTAMP,
    criado_por     VARCHAR(180),
    atualizado_por VARCHAR(180),
    CONSTRAINT fk_refeicao_plano FOREIGN KEY (plano_id) REFERENCES plano_alimentar (id)
);

CREATE INDEX ix_refeicao_plano ON refeicao (plano_id);

CREATE TABLE item_refeicao (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refeicao_id      BIGINT       NOT NULL,
    alimento_id      BIGINT,
    medida_id        BIGINT,
    descricao        VARCHAR(250) NOT NULL,
    descricao_medida VARCHAR(120),
    quantidade       DECIMAL(10,3),
    -- Peso congelado na edicao: corrigir a porcao depois nao reescreve um
    -- plano ja entregue ao paciente.
    gramas           DECIMAL(10,3),
    ordem            INTEGER      NOT NULL,
    observacao       VARCHAR(500),
    criado_em        TIMESTAMP    NOT NULL,
    atualizado_em    TIMESTAMP,
    criado_por       VARCHAR(180),
    atualizado_por   VARCHAR(180),
    CONSTRAINT fk_item_refeicao FOREIGN KEY (refeicao_id) REFERENCES refeicao (id),
    CONSTRAINT fk_item_alimento FOREIGN KEY (alimento_id) REFERENCES alimento (id),
    CONSTRAINT ck_item_quantidade CHECK (quantidade IS NULL OR quantidade > 0),
    CONSTRAINT ck_item_gramas     CHECK (gramas     IS NULL OR gramas     > 0)
);

CREATE INDEX ix_item_refeicao ON item_refeicao (refeicao_id);
CREATE INDEX ix_item_alimento ON item_refeicao (alimento_id);

CREATE TABLE equivalente_item (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id          BIGINT       NOT NULL,
    alimento_id      BIGINT,
    medida_id        BIGINT,
    descricao        VARCHAR(250) NOT NULL,
    descricao_medida VARCHAR(120),
    quantidade       DECIMAL(10,3),
    gramas           DECIMAL(10,3),
    criado_em        TIMESTAMP    NOT NULL,
    atualizado_em    TIMESTAMP,
    criado_por       VARCHAR(180),
    atualizado_por   VARCHAR(180),
    CONSTRAINT fk_equivalente_item     FOREIGN KEY (item_id)     REFERENCES item_refeicao (id),
    CONSTRAINT fk_equivalente_alimento FOREIGN KEY (alimento_id) REFERENCES alimento (id)
);

CREATE INDEX ix_equivalente_item ON equivalente_item (item_id);
