-- Avaliação antropométrica.
--
-- A tabela guarda medidas brutas E resultados derivados (percentual de gordura,
-- gasto energético), junto do protocolo e da equação que os produziram.
--
-- Guardar o derivado é deliberado: recalcular na leitura faria uma avaliação
-- antiga mudar de valor porque a implementação evoluiu, e o histórico do
-- paciente deixaria de ser comparável consigo mesmo. As medidas brutas ficam
-- ao lado para permitir reconferir a conta.

CREATE TABLE avaliacao_antropometrica (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conta_id              BIGINT NOT NULL,
    paciente_id           BIGINT NOT NULL,
    data                  DATE   NOT NULL,

    peso_kg               DECIMAL(6,2),
    altura_cm             DECIMAL(6,2),

    dobra_tricipital      DECIMAL(6,2),
    dobra_bicipital       DECIMAL(6,2),
    dobra_subescapular    DECIMAL(6,2),
    dobra_suprailiaca     DECIMAL(6,2),
    dobra_abdominal       DECIMAL(6,2),
    dobra_peitoral        DECIMAL(6,2),
    dobra_coxa            DECIMAL(6,2),
    dobra_panturrilha     DECIMAL(6,2),
    dobra_axilar_media    DECIMAL(6,2),

    circ_cintura          DECIMAL(6,2),
    circ_quadril          DECIMAL(6,2),
    circ_abdomen          DECIMAL(6,2),
    circ_braco            DECIMAL(6,2),
    circ_antebraco        DECIMAL(6,2),
    circ_coxa             DECIMAL(6,2),
    circ_panturrilha      DECIMAL(6,2),
    circ_torax            DECIMAL(6,2),

    protocolo_composicao  VARCHAR(30),
    percentual_gordura    DECIMAL(5,2),
    massa_gorda_kg        DECIMAL(6,2),
    massa_magra_kg        DECIMAL(6,2),

    equacao_gasto         VARCHAR(30),
    fator_atividade       DECIMAL(4,2),
    gasto_basal_kcal      DECIMAL(8,2),
    gasto_total_kcal      DECIMAL(8,2),

    observacoes           VARCHAR(2000),

    criado_em             TIMESTAMP NOT NULL,
    atualizado_em         TIMESTAMP,
    criado_por            VARCHAR(180),
    atualizado_por        VARCHAR(180),

    CONSTRAINT fk_avaliacao_conta    FOREIGN KEY (conta_id)    REFERENCES conta (id),
    CONSTRAINT fk_avaliacao_paciente FOREIGN KEY (paciente_id) REFERENCES paciente (id),

    -- Medida negativa ou nula não é medida. Zero num campo antropométrico é
    -- quase sempre digitação incompleta, não observação.
    CONSTRAINT ck_avaliacao_peso   CHECK (peso_kg   IS NULL OR peso_kg   > 0),
    CONSTRAINT ck_avaliacao_altura CHECK (altura_cm IS NULL OR altura_cm > 0),
    CONSTRAINT ck_avaliacao_gordura CHECK (
        percentual_gordura IS NULL OR (percentual_gordura >= 0 AND percentual_gordura <= 100)
    ),
    -- Composição estimada exige o protocolo que a produziu: sem ele o número
    -- não é reconferível nem comparável.
    CONSTRAINT ck_avaliacao_protocolo CHECK (
        percentual_gordura IS NULL OR protocolo_composicao IS NOT NULL
    )
);

CREATE INDEX ix_avaliacao_conta    ON avaliacao_antropometrica (conta_id);
CREATE INDEX ix_avaliacao_paciente ON avaliacao_antropometrica (paciente_id, data);
