-- Agenda de atendimentos.
--
-- O intervalo é guardado como início mais duração, e não como início e fim:
-- duração é o que o profissional informa, e derivar o fim elimina o estado
-- inconsistente de um fim anterior ao início.

CREATE TABLE agendamento (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conta_id        BIGINT    NOT NULL,
    paciente_id     BIGINT    NOT NULL,
    inicio          TIMESTAMP NOT NULL,
    duracao_minutos INTEGER   NOT NULL,
    tipo            VARCHAR(30) NOT NULL,
    situacao        VARCHAR(20) NOT NULL,
    observacao      VARCHAR(1000),
    motivo_desfecho VARCHAR(500),
    criado_em       TIMESTAMP NOT NULL,
    atualizado_em   TIMESTAMP,
    criado_por      VARCHAR(180),
    atualizado_por  VARCHAR(180),

    CONSTRAINT fk_agendamento_conta    FOREIGN KEY (conta_id)    REFERENCES conta (id),
    CONSTRAINT fk_agendamento_paciente FOREIGN KEY (paciente_id) REFERENCES paciente (id),
    CONSTRAINT ck_agendamento_duracao  CHECK (duracao_minutos > 0 AND duracao_minutos <= 600)
);

-- Consulta quente: a agenda de um dia, e a verificação de conflito, ambas
-- percorrem a conta por faixa de início.
CREATE INDEX ix_agendamento_conta    ON agendamento (conta_id, inicio);
CREATE INDEX ix_agendamento_paciente ON agendamento (paciente_id);
