-- Lançamentos financeiros do consultório.
--
-- O valor é sempre positivo: o que distingue entrada de saída é a coluna tipo.
-- Guardar despesa como número negativo espalharia a regra por toda soma do
-- sistema, e um esquecimento transformaria despesa em receita.
--
-- As três datas têm papéis distintos: competência diz a que mês o lançamento
-- pertence, vencimento diz quando deveria ser pago, e data_pagamento diz quando
-- efetivamente entrou. É essa separação que permite apurar caixa e competência
-- sem misturar um com o outro.

CREATE TABLE lancamento_financeiro (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conta_id        BIGINT        NOT NULL,
    tipo            VARCHAR(20)   NOT NULL,
    situacao        VARCHAR(20)   NOT NULL,
    valor           DECIMAL(12,2) NOT NULL,
    competencia     DATE          NOT NULL,
    vencimento      DATE,
    data_pagamento  DATE,
    categoria       VARCHAR(80)   NOT NULL,
    forma_pagamento VARCHAR(40),
    descricao       VARCHAR(500),
    paciente_id     BIGINT,
    agendamento_id  BIGINT,
    criado_em       TIMESTAMP     NOT NULL,
    atualizado_em   TIMESTAMP,
    criado_por      VARCHAR(180),
    atualizado_por  VARCHAR(180),

    CONSTRAINT fk_lancamento_conta       FOREIGN KEY (conta_id)       REFERENCES conta (id),
    CONSTRAINT fk_lancamento_paciente    FOREIGN KEY (paciente_id)    REFERENCES paciente (id),
    CONSTRAINT fk_lancamento_agendamento FOREIGN KEY (agendamento_id) REFERENCES agendamento (id),

    CONSTRAINT ck_lancamento_valor CHECK (valor > 0),

    -- Pago exige data de pagamento; pendente não pode tê-la. Sem isso, uma
    -- apuração por caixa somaria lançamento sem saber quando ele entrou.
    CONSTRAINT ck_lancamento_pagamento CHECK (
        (situacao = 'PAGO'     AND data_pagamento IS NOT NULL) OR
        (situacao <> 'PAGO'    AND data_pagamento IS NULL)
    )
);

CREATE INDEX ix_lancamento_conta      ON lancamento_financeiro (conta_id, competencia);
CREATE INDEX ix_lancamento_paciente   ON lancamento_financeiro (paciente_id);
CREATE INDEX ix_lancamento_vencimento ON lancamento_financeiro (conta_id, situacao, vencimento);
